remote_theme: pages-themes/cayman@v0.2.0
plugins:
  - jekyll-remote-theme # add this line to the plugins list if you already have one
  - jekyll-seo-tag
title: Reusable Bicep Modules
baseurl: /reusable-bicep-modules
tagline: Azure reusable bicep modules | infrastructure-as-code
description: Deploy Azure resources with reusable Bicep modules
tags: [Bicep, Azure, iac,infrastructure-as-code, reusable, modules]