remote_theme: pages-themes/cayman@v0.2.0
plugins:
  - jekyll-remote-theme # add this line to the plugins list if you already have one
  - jekyll-seo-tag
title: Reusable Bicep Building-Blocks
baseurl: /bicep-building-blocks
tagline: Azure reusable bicep building-blocks | infrastructure-as-code
description: Deploy Azure resources with reusable building-blocks defined in the Bicep language